CREATE PROCEDURE dbo.usp_GiangVien_Login
    @LoginName NVARCHAR(128)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CASE
            WHEN IS_MEMBER('PGV') = 1 THEN 'PGV'
            ELSE 'Giangvien'
        END AS UserRole;
END
GO

CREATE PROCEDURE dbo.usp_SinhVien_Login
    @MASV NVARCHAR(50),
    @PASSWORD NVARCHAR(128)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MASV, HO, TEN, MALOP
    FROM SINHVIEN
    WHERE MASV = @MASV
      AND MATKHAU = @PASSWORD;
END
GO

