-- ============================================================
-- FILE: M01_Schema_And_Constraints.sql
-- MUC DICH: Gom tat ca cac thay doi ve Schema, Constraints va Indexes:
--   1. Them cot MATKHAU vao bang SINHVIEN (tu 000)
--   2. Them NOT NULL va UNIQUE vao MONHOC.TENMH (tu 001)
--   3. Them UNIQUE vao LOP.TENLOP (tu 001)
--   4. Tao cac Index IX_BODE_MAGV, IX_BODE_MAMH_TRINHDO, IX_SINHVIEN_MALOP (tu 001)
--   5. Mo rong SINHVIEN.DIACHI len NVARCHAR(100) (tu 006)
--   6. Them Foreign Key BODE.MAGV -> GIAOVIEN(MAGV) (tu 007)
--   7. Them CHECK constraint CK_SINHVIEN_NGAYSINH (tu 008)
--   8. Them Index IX_BODE_MAGV_MAMH (tu 009)
-- ============================================================
USE [THITRACNGHIEM]
GO

-- 1. Them cot MATKHAU vao bang SINHVIEN
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME  = 'SINHVIEN'
      AND COLUMN_NAME = 'MATKHAU'
)
BEGIN
    ALTER TABLE [dbo].[SINHVIEN]
    ADD [MATKHAU] NVARCHAR(128) NULL;
    PRINT N'OK: Đã thêm cột MATKHAU vào bảng SINHVIEN.';
END
ELSE
BEGIN
    PRINT N'SKIP: Cột MATKHAU đã tồn tại trong bảng SINHVIEN.';
END
GO

-- 2. MONHOC.TENMH -> NOT NULL
IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME  = 'MONHOC'
      AND COLUMN_NAME = 'TENMH'
      AND IS_NULLABLE = 'YES'
)
BEGIN
    IF EXISTS (SELECT 1 FROM [dbo].[MONHOC] WHERE TENMH IS NULL)
    BEGIN
        RAISERROR(N'MONHOC.TENMH có dữ liệu NULL. Hãy cập nhật dữ liệu trước khi chạy lệnh này.', 16, 1);
        RETURN;
    END

    ALTER TABLE [dbo].[MONHOC]
    ALTER COLUMN [TENMH] NVARCHAR(40) NOT NULL;
    PRINT N'OK: MONHOC.TENMH đã được đặt thành NOT NULL.';
END
ELSE
BEGIN
    PRINT N'SKIP: MONHOC.TENMH đã là NOT NULL.';
END
GO

-- 3. MONHOC.TENMH -> UNIQUE
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME       = 'MONHOC'
      AND CONSTRAINT_NAME  = 'UQ_MONHOC_TENMH'
      AND CONSTRAINT_TYPE  = 'UNIQUE'
)
BEGIN
    IF EXISTS (
        SELECT TENMH FROM [dbo].[MONHOC]
        GROUP BY TENMH
        HAVING COUNT(*) > 1
    )
    BEGIN
        RAISERROR(N'MONHOC.TENMH có dữ liệu trùng. Hãy xử lý trước khi thêm UNIQUE constraint.', 16, 1);
        RETURN;
    END

    ALTER TABLE [dbo].[MONHOC]
    ADD CONSTRAINT [UQ_MONHOC_TENMH] UNIQUE ([TENMH]);
    PRINT N'OK: Đã thêm UNIQUE constraint UQ_MONHOC_TENMH.';
END
ELSE
BEGIN
    PRINT N'SKIP: UQ_MONHOC_TENMH đã tồn tại.';
END
GO

-- 4. LOP.TENLOP -> UNIQUE
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME       = 'LOP'
      AND CONSTRAINT_NAME  = 'UQ_LOP_TENLOP'
      AND CONSTRAINT_TYPE  = 'UNIQUE'
)
BEGIN
    IF EXISTS (
        SELECT TENLOP FROM [dbo].[LOP]
        GROUP BY TENLOP
        HAVING COUNT(*) > 1
    )
    BEGIN
        RAISERROR(N'LOP.TENLOP có dữ liệu trùng. Hãy xử lý trước khi thêm UNIQUE constraint.', 16, 1);
        RETURN;
    END

    ALTER TABLE [dbo].[LOP]
    ADD CONSTRAINT [UQ_LOP_TENLOP] UNIQUE ([TENLOP]);
    PRINT N'OK: Đã thêm UNIQUE constraint UQ_LOP_TENLOP.';
END
ELSE
BEGIN
    PRINT N'SKIP: UQ_LOP_TENLOP đã tồn tại.';
END
GO

-- 5. INDEX: IX_BODE_MAGV
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_BODE_MAGV'
      AND object_id = OBJECT_ID('BODE')
)
BEGIN
    CREATE INDEX [IX_BODE_MAGV] ON [dbo].[BODE] ([MAGV]);
    PRINT N'OK: Đã tạo index IX_BODE_MAGV.';
END
ELSE
BEGIN
    PRINT N'SKIP: Index IX_BODE_MAGV đã tồn tại.';
END
GO

-- 6. INDEX: IX_BODE_MAMH_TRINHDO
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_BODE_MAMH_TRINHDO'
      AND object_id = OBJECT_ID('BODE')
)
BEGIN
    CREATE INDEX [IX_BODE_MAMH_TRINHDO] ON [dbo].[BODE] ([MAMH], [TRINHDO]);
    PRINT N'OK: Đã tạo index IX_BODE_MAMH_TRINHDO.';
END
ELSE
BEGIN
    PRINT N'SKIP: Index IX_BODE_MAMH_TRINHDO đã tồn tại.';
END
GO

-- 7. INDEX: IX_SINHVIEN_MALOP
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_SINHVIEN_MALOP'
      AND object_id = OBJECT_ID('SINHVIEN')
)
BEGIN
    CREATE INDEX [IX_SINHVIEN_MALOP] ON [dbo].[SINHVIEN] ([MALOP]);
    PRINT N'OK: Đã tạo index IX_SINHVIEN_MALOP.';
END
ELSE
BEGIN
    PRINT N'SKIP: Index IX_SINHVIEN_MALOP đã tồn tại.';
END
GO

-- 8. Mo rong SINHVIEN.DIACHI len NVARCHAR(100)
IF EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME  = 'SINHVIEN'
      AND COLUMN_NAME = 'DIACHI'
      AND CHARACTER_MAXIMUM_LENGTH < 100
)
BEGIN
    ALTER TABLE [dbo].[SINHVIEN]
    ALTER COLUMN [DIACHI] NVARCHAR(100) NULL;
    PRINT N'OK: Da mo rong SINHVIEN.DIACHI len NVARCHAR(100).';
END
ELSE
BEGIN
    PRINT N'SKIP: SINHVIEN.DIACHI da >= 100 ky tu.';
END
GO

-- 9. Them Foreign Key BODE.MAGV -> GIAOVIEN(MAGV)
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME      = 'BODE'
      AND CONSTRAINT_NAME = 'FK_BODE_GIAOVIEN'
      AND CONSTRAINT_TYPE = 'FOREIGN KEY'
)
BEGIN
    ALTER TABLE [dbo].[BODE]
    ADD CONSTRAINT [FK_BODE_GIAOVIEN]
        FOREIGN KEY ([MAGV])
        REFERENCES [dbo].[GIAOVIEN] ([MAGV]);
    PRINT N'OK: Da them Foreign Key FK_BODE_GIAOVIEN.';
END
ELSE
BEGIN
    PRINT N'SKIP: FK_BODE_GIAOVIEN da ton tai.';
END
GO

-- 10. Them CHECK constraint CK_SINHVIEN_NGAYSINH
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME      = 'SINHVIEN'
      AND CONSTRAINT_NAME = 'CK_SINHVIEN_NGAYSINH'
      AND CONSTRAINT_TYPE = 'CHECK'
)
BEGIN
    IF EXISTS (
        SELECT 1 FROM [dbo].[SINHVIEN]
        WHERE NGAYSINH IS NOT NULL
          AND (NGAYSINH <= '1900-01-01' OR NGAYSINH >= GETDATE())
    )
    BEGIN
        RAISERROR(N'SINHVIEN.NGAYSINH co du lieu vi pham. Hay cap nhat du lieu truoc.', 16, 1);
        RETURN;
    END

    ALTER TABLE [dbo].[SINHVIEN]
    ADD CONSTRAINT [CK_SINHVIEN_NGAYSINH]
        CHECK (
            [NGAYSINH] IS NULL
            OR ([NGAYSINH] > '1900-01-01' AND [NGAYSINH] < GETDATE())
        );
    PRINT N'OK: Da them CHECK constraint CK_SINHVIEN_NGAYSINH.';
END
ELSE
BEGIN
    PRINT N'SKIP: CK_SINHVIEN_NGAYSINH da ton tai.';
END
GO

-- 11. Them Index IX_BODE_MAGV_MAMH
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name      = 'IX_BODE_MAGV_MAMH'
      AND object_id = OBJECT_ID('dbo.BODE')
)
BEGIN
    CREATE NONCLUSTERED INDEX [IX_BODE_MAGV_MAMH]
    ON [dbo].[BODE] ([MAGV] ASC, [MAMH] ASC);
    PRINT N'OK: Da tao index IX_BODE_MAGV_MAMH tren BODE(MAGV, MAMH).';
END
ELSE
BEGIN
    PRINT N'SKIP: Index IX_BODE_MAGV_MAMH da ton tai.';
END
GO

-- 12. Them cot TrangThai vao MONHOC va tao Filtered Index UQ_MONHOC_TENMH_Active
-- 12.1. Them cot TrangThai neu chua co
IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME  = 'MONHOC'
      AND COLUMN_NAME = 'TrangThai'
)
BEGIN
    ALTER TABLE [dbo].[MONHOC]
    ADD [TrangThai] BIT NOT NULL DEFAULT 1;
    PRINT N'OK: Đã thêm cột TrangThai vào bảng MONHOC.';
END
ELSE
BEGIN
    PRINT N'SKIP: Cột TrangThai đã tồn tại trong bảng MONHOC.';
END
GO

-- 12.2. Xoa unique constraint UQ_MONHOC_TENMH cu neu ton tai
IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_NAME       = 'MONHOC'
      AND CONSTRAINT_NAME  = 'UQ_MONHOC_TENMH'
      AND CONSTRAINT_TYPE  = 'UNIQUE'
)
BEGIN
    ALTER TABLE [dbo].[MONHOC] DROP CONSTRAINT [UQ_MONHOC_TENMH];
    PRINT N'OK: Đã xóa UNIQUE constraint UQ_MONHOC_TENMH cũ.';
END
GO

-- 12.3. Tao Filtered Unique Index cho TENMH voi TrangThai = 1
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name      = 'UQ_MONHOC_TENMH_Active'
      AND object_id = OBJECT_ID('dbo.MONHOC')
)
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_MONHOC_TENMH_Active]
    ON [dbo].[MONHOC] ([TENMH] ASC)
    WHERE [TrangThai] = 1;
    PRINT N'OK: Đã tạo Filtered Unique Index UQ_MONHOC_TENMH_Active.';
END
ELSE
BEGIN
    PRINT N'SKIP: Index UQ_MONHOC_TENMH_Active đã tồn tại.';
END
GO

