/* =========================================
FILE: migrate_BODE_add_identity_CAUHOI.sql
MỤC ĐÍCH:
- Chuyển CAUHOI -> INT IDENTITY(1,1)
- Giữ lại dữ liệu cũ
========================================= */
BEGIN TRANSACTION;

BEGIN TRY
ALTER TABLE BODE ADD CAUHOI_NEW INT IDENTITY (1, 1);

ALTER TABLE BODE
DROP CONSTRAINT PK_BODE;

ALTER TABLE BODE
DROP COLUMN CAUHOI;

EXEC sp_rename 'BODE.CAUHOI_NEW',
'CAUHOI',
'COLUMN';

ALTER TABLE BODE ADD CONSTRAINT PK_BODE PRIMARY KEY (CAUHOI);

COMMIT TRANSACTION;

END TRY BEGIN CATCH ROLLBACK TRANSACTION;

PRINT ERROR_MESSAGE ();

END CATCH;